<a href="https://colab.research.google.com/github/Kshitij-Panday/Aiml_Lab/blob/main/Kshitij_AIML_Lab2_EDA_Preprocessing_Workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Machine Learning Lab Experiment 2
# Topic: Exploratory Data Analysis, Data Preprocessing, and Data Visualization
# Prerequisite: Familiarity with Python, NumPy, Pandas

In [ ]:
# ================================
# Introduction
# ================================

In [ ]:
"""
This lab covers:
1. Exploratory Data Analysis (EDA)
2. Data Preprocessing techniques
3. Data Visualization
Each section includes explanations, code snippets, and tasks to reinforce learning.
"""

'\nThis lab covers:\n1. Exploratory Data Analysis (EDA)\n2. Data Preprocessing techniques\n3. Data Visualization\nEach section includes explanations, code snippets, and tasks to reinforce learning.\n'

In [ ]:
# ================================
# Importing Required Libraries
# ================================

In [ ]:
# Import necessary Python libraries for data manipulation, visualization, and preprocessing


import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [ ]:
#================================
# Load the Dataset
# ================================

view the first few or last few rows of a DataFrame using the .head() or .tail() methods, respectively. You can specify the number of rows through the n argument (the default value is 5).

In [ ]:
"""
Use any CSV file like Titanic, Iris, or a generic CSV with categorical and numerical features.
"""
# Load dataset using pandas and display the first few rows

() Parentheses uses 1) Call a function 2) ordering expressions, 3)In conditions (recommended for clarity with and/or)

[] Square brackets uses 1) Access DataFrame/Series columns (Pandas)2)indexing/slicing 3)Create a list (mutable sequence)

{} Curly braces
1) Create a dictionary (key → value)
d = {"name": "Asha", "score": 82}

2) Create a set (unique values)
s = {1, 2, 2, 3}   

Empty {} is a dict, not a set:

{}          # empty dict
set()       # empty set

Quick memory rule

() → call / group / tuple

[] → list / indexing / slicing

{} → dictionary / set

view the first few or last few rows of a DataFrame using the .head() or .tail() methods, respectively. You can specify the number of rows through the n argument (the default value is 5).

In [ ]:
#Display first 5 rows

In [ ]:
# Display last 5 rows

12

In [ ]:
# Display column names and data types

In [ ]:
print(df.shape)

df.shape # (rows, columns)
df.columns# column names
df.dtypes # data type of each column
df.head() # first 5 rows
df.tail()# last 5 rows
df.sample(5)# random 5 rows

In [ ]:
df.describe()

In [ ]:
df.describe(include=[int])

In [ ]:
df.describe(exclude=[int])

In [ ]:
df.info()
df.shape

df.info()                         # non-null counts + dtypes

df.describe ()                     #  gives numeric summaries (mean, std, min/max).

df.describe(include="object")     # categorical/text summary

df.nunique()                      # unique count per column

df.describe(exclude=[int]) #exclude certain data types
df.describe(include=[int])
isolate specific data types in your summary output by using the include argument

In [ ]:
# Generate descriptive statistics

In [ ]:
df.describe(include=[int])
#df.describe(exclude=[int])

In [ ]:
#print("Shape (rows, columns):", df.shape)
#print("\nColumns:", list(df.columns))
#print("\nData types:\n", df.dtypes)

In [ ]:
# calculate mean of age column

np.float64(29.7)

In [ ]:
#slicing
df.columns[2:12]

df.isna().sum() # missing count per column

df.isna().mean()*100 # missing % per column

df[df.isna().any(axis=1)] # rows that have any missing value

In [1]:
# VIMP Check for missing values
#df.isna() checks which values are missing in the DataFrame and returns a table of True/False:
# returns True → value is missing (NA/NaN)
#False → value is present
#df.isna().sum() # missing count per column
df.isnull().head(7) #shows only the first 7 rows of that True/False table.
#df.isnull().sum()  # isnull() and isna() are same

NameError: name 'df' is not defined

In [ ]:
#Check how many ages are missing (good practice)

In [ ]:
#Pandas will automatically ignore NaN by default
#df["Age"].mean(skipna=True)

np.int64(177)

In [ ]:
df["Age"].head(10)

In [ ]:
#df[["Age", "Fare", "Survived"]].head()
#df[condition].head() → head of filtered data
#df[df["Age"] > 50].head(5)
#df.sort_values("Fare", ascending=False).head(5)   # top 5 highest fares
#df.sort_values("Age", ascending=True).head(5)     # 5 youngest (ignoring NaN positions)
#df.groupby("Gender")["Survived"].mean().head()
df.describe(include="all")

1)	Default describe() (numeric columns only)
df.describe() #Gives count, mean, std, min, 25%, 50%, 75%, max for numeric columns.
2)  with rounding (clean output)
df.describe().round(2)

3) Describe only one column (Series)
df["Age"].describe()
df["Fare"].describe()

4) Describe specific columns
df[["Age", "Fare", "SibSp"]].describe()

5) Include categorical columns too (include="all")
df.describe(include="all")
For text/categorical columns it shows:	count, unique, top, freq

6) Describe only categorical (object) columns
df.describe(include=["object"])
Useful for columns like Name, Ticket, Cabin, Embarked, etc.

7) Describe both numeric + category explicitly
df.describe(include=["number", "object"])

8) Exclude some types (example: exclude object)
df.describe(exclude=["object"])

9) Control percentiles shown (good for outliers)
df.describe(percentiles=[0.01, 0.05, 0.5, 0.95, 0.99])
Helps see extreme values and skewness (important for ML preprocessing).

10) Transpose describe for readability (columns become rows)
df.describe().T
Very helpful when there are many numeric columns.

Quick Titanic-focused examples
df[["Age", "Fare"]].describe(percentiles=[0.1, 0.5, 0.9]).round(2)
df.describe(include=["object"]).T

In [ ]:
#slice indexing:3 = start index (included)11 = end index (excluded)

In [ ]:
missing_count = df.isna().sum()
print(missing_count)

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Check for duplicate rows
#Duplicates can bias training.
df.duplicated().sum()
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
#Target Variable Understanding: Survived (Text cell)
#In ML, we first study the target distribution (class balance).
df["Survived"].value_counts()
#0 usually means did not survive
#1 means survived

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
#Survival percentage
#df["Survived"].value_counts(normalize=True)
#df["Survived"].value_counts(normalize=True) * 100
#Include missing values (if any)
df["Survived"].value_counts(dropna=False)
df["Survived"].value_counts().plot(kind="bar")

Exercise1 Task 1 (Text cell)

Task: Print only the Age column and show:

first 8 values

how many missing values are in Age

In [ ]:
#solution Task1

Task 2
Task: Find the top 5 most common tickets (Ticket values).

In [ ]:
# solution Task2

Task: Find the survival rate by Gender (as percentage).

Step-by-step explanation
1) Groups the data into separate groups based on Gender:
one group for Female and one group for Male

use groupby() and use Gender attribute

 df.groupby("Gender")

 2) From each group, select only the Survived column.["Survived"]



3)Compute the average of Survived for each gender.
 .mean()

Survival rate by Gender (in %)
Survived is usually: 1 =survived
0 = not survived
So the average (mean) of 0/1 becomes a rate.

Example: if among females [1, 1, 0, 1]
Mean = (1+1+0+1)/4 = 0.75 → 75% survival rate

In [ ]:
#Task: Find the survival rate by Gender (as percentage).
grouped = df.groupby("Gender")
#print(grouped.groups.keys()) #See group names (Male/Female)
#print(grouped.get_group("male").head()) #Get one group and print it (e.g., Male)
#print (grouped.shape ())
#(df.groupby("Gender")["Survived"].mean() * 100).round(2)
for gender, data in grouped:
    print("\nGender:", gender)
    print("Rows:", len(data))
    print(data.head(3))

value_counts() counts how many times each unique value appears in a column (Series).

Most common use in EDA to check category distribution and class balance.

In [ ]:
# View value counts of categorical columns (e.g., Gender, Embarked)
df['Gender'].value_counts()
df['Embarked'].value_counts()
#df["Gender"].value_counts(normalize=True) * 100
#for col in ["Gender", "Embarked", "Pclass"]:
#print("\n", col)
#print(df[col].value_counts(dropna=False))

In [ ]:
# ================================
# 2. Handling Missing Data
# ================================

In [ ]:
df.isna().sum()

In [ ]:
df1=df.copy()
df1.head (30)

1) Copy an existing DataFrame (most common)
df2 = df.copy()

Use this when you want a new DataFrame without changing the original.

2) Create from a dictionary (columns → lists)
df3 = pd.DataFrame({
    "name": ["Asha", "Ravi", "Neha"],
    "score": [82, 75, 90],
    "passed": [1, 1, 1]
})

3) Create a DataFrame from selected columns of another
df4 = df[["Age", "Fare", "Survived"]].copy()

4) Create a DataFrame by filtering rows
df5 = df[df["Age"] > 60].copy()

5) Create a DataFrame by dropping columns
df6 = df.drop(columns=["Cabin", "Ticket"]).copy()

6) Create an empty DataFrame (then fill later)
df7 = pd.DataFrame(columns=["A", "B", "C"])

In [ ]:
df6=df.copy()
df6.shape
df6.columns
df10=df.drop(columns=["PassengerId","Name","Cabin"])
df10.shape

In [ ]:
df11=df.drop(columns=["Cabin", "Ticket"]).copy()
df11.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age', 'SibSp',
       'Parch', 'Fare', 'Embarked'],
      dtype='object')

In [ ]:
# Apply imputation strategy to fill missing numerical values (e.g., Age)
num_imputer = SimpleImputer(strategy = 'median')
#num_imputer.fit(df[['Age']])
#df['Age'] = num_imputer.transform(df[['Age']])


df['Age'] = num_imputer.fit_transform(df[['Age']])

In [ ]:
df['Age'].isnull().sum()

np.int64(0)

In [ ]:
df['Embarked']

In [ ]:
missing = df.isna().sum()
missing_pct = (df.isna().mean()*100).round(2)
print(pd.DataFrame({"missing": missing, "missing_%": missing_pct}).sort_values("missing", ascending=False))

Column-by-column strategy (ML perspective)
1) PassengerId (0 missing) Role: Identifier only  Action: Drop before ML (not useful for prediction)

2) Survived (0 missing)Role: Target/Label
Action: Keep as y

3) Pclass (0 missing)
Role: Important feature (ordinal category 1/2/3)
Action: Keep; later encode as numeric/one-hot (your choice)

4) Name (0 missing)
Role: Raw text (not directly ML-friendly)
Best use: Extract Title (Mr/Mrs/Miss/etc.) then drop Name
Action: Keep temporarily for feature engineering

5) Gender (0 missing)
Role: Strong categorical predictor
Action: Keep; encode later (male/female → 0/1 or one-hot)

6) Age (177 missing ~19.87%)
Role: Important numeric feature
Best strategy: Impute + add missing flag

Create Age_missing = 1 if Age is missing else 0
Fill missing Age using a smart median:
Better: median by (Pclass, Gender) or (Title, Pclass)
Simpler: overall median

Impute Age by median of (Pclass, Gender) + add Age_missing

7) SibSp (0 missing)
Role: Useful numeric feature
Action: Keep; engineer FamilySize = SibSp + Parch + 1, IsAlone

8) Parch (0 missing)
Role: Useful numeric feature
Action: Keep; used in FamilySize

9) Ticket (0 missing)
Role: High-cardinality text (many unique values)
Action: Usually drop for baseline ML

10) Fare (0 missing)
Role: Important numeric feature (often skewed/outliers)
Action: Keep


11) Cabin (687 missing ~77.10%)
Role: Very sparse text feature
Best strategy: Don’t use raw Cabin directly
Choose one approach:
Option A (simplest baseline):Drop Cabin entirely

Option B (ML-friendly + valuable):Create CabinKnown (0/1)

Create Deck = first letter of cabin (A/B/C/...) and fill missing as "Unknown"
Then drop raw Cabin

Recommended for teaching ML thinking:
Use Deck + CabinKnown, drop Cabin

12) Embarked (2 missing ~0.22%)
Role: Small categorical feature
Action: Fill missing with mode (most frequent value), then encode

In [ ]:
df1=df.copy()
df1.head (30)

In [ ]:
cat_imputer = SimpleImputer(strategy='most_frequent')
df['Embarked'] = df['Embarked'].astype('category')
df['Embarked'] = cat_imputer.fit_transform(df[['Embarked']]).ravel()

In [ ]:
df['Embarked'].isnull().sum()

np.int64(0)

In [ ]:
# Apply imputation strategy to fill missing categorical values (e.g., Embarked)

In [ ]:
# ================================
# 3. Removing Duplicate Entries
# ================================

In [ ]:
# Remove duplicate rows from the dataset

In [ ]:
# ================================
# 4. Outlier Detection and Treatment
# ================================

In [ ]:
# Use the IQR method to detect outliers in numerical features (e.g., Fare)
Q1 =df['Fare'].quantile(0.25)
Q2 =df['Fare'].quantile(0.50)
Q3 =df['Fare'].quantile(0.75)
IQR =Q3-Q1

In [ ]:
# Optionally remove or transform detected outliers

In [ ]:
# ================================
# 5. Encoding Categorical Variables
# ================================

In [ ]:
# Apply label encoding to Gender column

In [ ]:
# Apply one-hot encoding to categorical variables (e.g., Embarked)

In [ ]:
# ================================
# 6. Feature Scaling
# ================================

In [ ]:
# Apply standardization or normalization to numerical features (e.g., Age, Fare)

In [ ]:
# ================================
# 7. Feature Engineering
# ================================

In [ ]:
# Create new features (e.g., FamilySize = SibSp + Parch + 1)

In [ ]:
# ================================
# 8. Feature Selection
# ================================

In [ ]:
# Use filter methods like SelectKBest to select top features

In [ ]:
# Use wrapper methods like RFE to rank features

In [ ]:
# ================================
# 9. Splitting Dataset
# ================================

In [ ]:
# Split the dataset into training and test sets using train_test_split

In [ ]:
# ================================
# 10. Visualization
# ================================

In [ ]:
# Plot histograms to understand distributions (e.g., Age)

In [ ]:
# Create scatter plots to explore relationships (e.g., Fare vs Age colored by Survived)

In [ ]:
# Display a heatmap to show feature correlations

In [ ]:
# ================================
# Lab Exercises
# ================================
"""
1. Load a different dataset (e.g., Iris or any from UCI repo).
2. Perform similar EDA steps on it.
3. Try different imputation strategies.
4. Detect and visualize outliers in at least two features.
5. Create 2 new features based on domain knowledge.
6. Apply both standardization and normalization and compare.
7. Use feature selection and plot feature importance.
8. Divide the dataset and plot the training vs testing distributions.
9. Visualize data using pair plots or violin plots.
10. Write a short report on insights found from the EDA.
"""

'\n1. Load a different dataset (e.g., Iris or any from UCI repo).\n2. Perform similar EDA steps on it.\n3. Try different imputation strategies.\n4. Detect and visualize outliers in at least two features.\n5. Create 2 new features based on domain knowledge.\n6. Apply both standardization and normalization and compare.\n7. Use feature selection and plot feature importance.\n8. Divide the dataset and plot the training vs testing distributions.\n9. Visualize data using pair plots or violin plots.\n10. Write a short report on insights found from the EDA.\n'

In [ ]:
# END OF LAB 1 NOTEBOOK

In [ ]:
from google.colab import files
import io

uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

df = pd.read_csv('titanic.csv')

print(df.to_string())

     PassengerId  Survived  Pclass                                                                                Name  Gender    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                                                             Braund, Mr. Owen Harris    male  22.00      1      0           A/5 21171    7.2500              NaN        S
1              2         1       1                                 Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.00      1      0            PC 17599   71.2833              C85        C
2              3         1       3                                                              Heikkinen, Miss. Laina  female  26.00      0      0    STON/O2. 3101282    7.9250              NaN        S
3              4         1       1                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1      0              113803   53.1000             C123        S
4              5         0       3                                                            Allen, Mr. William Henry    male  35.00      0      0              373450    8.0500              NaN        S
5              6         0       3                                                                    Moran, Mr. James    male    NaN      0      0              330877    8.4583              NaN        Q
6              7         0       1                                                             McCarthy, Mr. Timothy J    male  54.00      0      0               17463   51.8625              E46        S
7              8         0       3                                                      Palsson, Master. Gosta Leonard    male   2.00      3      1              349909   21.0750              NaN        S
8              9         1       3                                   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0      2              347742   11.1333              NaN        S
9             10         1       2                                                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1      0              237736   30.0708              NaN        C
10            11         1       3                                                     Sandstrom, Miss. Marguerite Rut  female   4.00      1      1             PP 9549   16.7000               G6        S
11            12         1       1                                                            Bonnell, Miss. Elizabeth  female  58.00      0      0              113783   26.5500             C103        S
12            13         0       3                                                      Saundercock, Mr. William Henry    male  20.00      0      0           A/5. 2151    8.0500              NaN        S
13            14         0       3                                                         Andersson, Mr. Anders Johan    male  39.00      1      5              347082   31.2750              NaN        S
14            15         0       3                                                Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0      0              350406    7.8542              NaN        S
15            16         1       2                                                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0      0              248706   16.0000              NaN        S
16            17         0       3                                                                Rice, Master. Eugene    male   2.00      4      1              382652   29.1250              NaN        Q
17            18         1       2                                                        Williams, Mr. Charles Eugene    male    NaN      0      0              244373   13.0000              NaN        S
18            19         0       3                             Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)  female  31.00      1      0              345763   18.0000              NaN        S
19            20         1       3                                                             Masselmani, Mrs. Fatima  female    NaN      0      0                2649    7.2250              NaN        C
20            21         0       2                                                                Fynney, Mr. Joseph J    male  35.00      0      0              239865   26.0000              NaN        S
21            22         1       2                                                               Beesley, Mr. Lawrence    male  34.00      0      0              248698   13.0000              D56        S
22            23         1       3                                                         McGowan, Miss. Anna "Annie"  female  15.00      0      0              330923    8.0292              NaN        Q
23            24         1       1                                                        Sloper, Mr. William Thompson    male  28.00      0      0              113788   35.5000               A6        S
24            25         0       3                                                       Palsson, Miss. Torborg Danira  female   8.00      3      1              349909   21.0750              NaN        S
25            26         1       3                           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.00      1      5              347077   31.3875              NaN        S
26            27         0       3                                                             Emir, Mr. Farred Chehab    male    NaN      0      0                2631    7.2250              NaN        C
27            28         0       1                                                      Fortune, Mr. Charles Alexander    male  19.00      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                                                       O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959    7.8792              NaN        Q
29            30         0       3                                                                 Todoroff, Mr. Lalio    male    NaN      0      0              349216    7.8958              NaN        S
30            31         0       1                                                            Uruchurtu, Don. Manuel E    male  40.00      0      0            PC 17601   27.7208              NaN        C
31            32         1       1                                      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569  146.5208              B78        C
32            33         1       3                                                            Glynn, Miss. Mary Agatha  female    NaN      0      0              335677    7.7500              NaN        Q
33            34         0       2                                                               Wheadon, Mr. Edward H    male  66.00      0      0          C.A. 24579   10.5000              NaN        S
34            35         0       1                                                             Meyer, Mr. Edgar Joseph    male  28.00      1      0            PC 17604   82.1708              NaN        C
35            36         0       1                                                      Holverson, Mr. Alexander Oskar    male  42.00      1      0              113789   52.0000              NaN        S
36            37         1       3                                                                    Mamee, Mr. Hanna    male    NaN      0      0                2677    7.2292              NaN        C
37            38         0       3                                                            Cann, Mr. Ernest Charles    male  21.00      0      0          A./5. 2152    8.0500              NaN        S
38            39         0       3                                                  Vander Planke, Miss. Augusta Maria  female  18.00      2      0              345764   18.0000              NaN        S
39            40         1       3                                                         Nicola-Yarred, Miss. Jamila  female  14.00      1      0                2651   11.2417              NaN        C
40            41         0       3                                      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1      0                7546    9.4750              NaN        S
41            42         0       2                            Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female  27.00      1      0               11668   21.0000              NaN        S
42            43         0       3                                                                 Kraeff, Mr. Theodor    male    NaN      0      0              349253    7.8958              NaN        C
43            44         1       2                                            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1      2       SC/Paris 2123   41.5792              NaN        C
44            45         1       3                                                       Devaney, Miss. Margaret Delia  female  19.00      0      0              330958    7.8792              NaN        Q
45            46         0       3                                                            Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567    8.0500              NaN        S
46            47         0       3                                                                   Lennon, Mr. Denis    male    NaN      1      0              370371   15.5000              NaN        Q
47            48         1       3                                                           O'Driscoll, Miss. Bridget  female    NaN      0      0               14311    7.7500              NaN        Q
48            49         0       3                                                                 Samaan, Mr. Youssef    male    NaN      2      0                2662   21.6792              NaN        C
49            50         0       3                                       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1      0              349237   17.8000              NaN        S
50            51         0       3                                                          Panula, Master. Juha Niilo    male   7.00      4      1             3101295   39.6875              NaN        S
51            52         0       3                                                        Nosworthy, Mr. Richard Cater    male  21.00      0      0          A/4. 39886    7.8000              NaN        S
52            53         1       1                                            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1      0            PC 17572   76.7292              D33        C
53            54         1       2                                  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)  female  29.00      1      0                2926   26.0000              NaN        S
54            55         0       1                                                      Ostby, Mr. Engelhart Cornelius    male  65.00      0      1              113509   61.9792              B30        C
55            56         1       1                                                                   Woolner, Mr. Hugh    male    NaN      0      0               19947   35.5000              C52        S
56            57         1       2                                                                   Rugg, Miss. Emily  female  21.00      0      0          C.A. 31026   10.5000              NaN        S
57            58         0       3                                                                 Novel, Mr. Mansouer    male  28.50      0      0                2697    7.2292              NaN        C
58            59         1       2                                                        West, Miss. Constance Mirium  female   5.00      1      2          C.A. 34651   27.7500              NaN        S
59            60         0       3                                                  Goodwin, Master. William Frederick    male  11.00      5      2             CA 2144   46.9000              NaN        S
60            61         0       3                                                               Sirayanian, Mr. Orsen    male  22.00      0      0                2669    7.2292              NaN        C
61            62         1       1                                                                 Icard, Miss. Amelie  female  38.00      0      0              113572   80.0000              B28      NaN
62            63         0       1                                                         Harris, Mr. Henry Birkhardt    male  45.00      1      0               36973   83.4750              C83        S
63            64         0       3                                                               Skoog, Master. Harald    male   4.00      3      2              347088   27.9000              NaN        S
64            65         0       1                                                               Stewart, Mr. Albert A    male    NaN      0      0            PC 17605   27.7208              NaN        C
65            66         1       3                                                            Moubarek, Master. Gerios    male    NaN      1      1                2661   15.2458              NaN        C
66            67         1       2                                                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                                                            Crease, Mr. Ernest James    male  19.00      0      0           S.P. 3464    8.1583              NaN        S
68            69         1       3                                                     Andersson, Miss. Erna Alexandra  female  17.00      4      2             3101281    7.9250              NaN        S
69            70         0       3                                                                   Kink, Mr. Vincenz    male  26.00      2      0              315151    8.6625              NaN        S
70            71         0       2                                                          Jenkin, Mr. Stephen Curnow    male  32.00      0      0          C.A. 33111   10.5000              NaN        S
71            72         0       3                                                          Goodwin, Miss. Lillian Amy  female  16.00      5      2             CA 2144   46.9000              NaN        S
72            73         0       2                                                                Hood, Mr. Ambrose Jr    male  21.00      0      0        S.O.C. 14879   73.5000              NaN        S
73            74         0       3                                                         Chronopoulos, Mr. Apostolos    male  26.00      1      0                2680   14.4542              NaN        C
74            75         1       3                                                                       Bing, Mr. Lee    male  32.00      0      0                1601   56.4958              NaN        S
75            76         0       3                                                             Moen, Mr. Sigurd Hansen    male  25.00      0      0              348123    7.6500            F G73        S
76            77         0       3                                                                   Staneff, Mr. Ivan    male    NaN      0      0              349208    7.8958              NaN        S
77            78         0       3                                                            Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746    8.0500              NaN        S
78            79         1       2                                                       Caldwell, Master. Alden Gates    male   0.83      0      2              248738   29.0000              NaN        S
79            80         1       3                                                            Dowdell, Miss. Elizabeth  female  30.00      0      0              364516   12.4750              NaN        S
80            81         0       3                                                                Waelens, Mr. Achille    male  22.00      0      0              345767    9.0000              NaN        S
81            82         1       3                                                         Sheerlinck, Mr. Jan Baptist    male  29.00      0      0              345779    9.5000              NaN        S
82            83         1       3                                                      McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932    7.7875              NaN        Q
83            84         0       1                                                             Carrau, Mr. Francisco M    male  28.00      0      0              113059   47.1000              NaN        S
84            85         1       2                                                                 Ilett, Miss. Bertha  female  17.00      0      0          SO/C 14885   10.5000              NaN        S
85            86         1       3                             Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)  female  33.00      3      0             3101278   15.8500              NaN        S
86            87         0       3                                                              Ford, Mr. William Neal    male  16.00      1      3          W./C. 6608   34.3750              NaN        S
87            88         0       3                                                       Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086    8.0500              NaN        S
88            89         1       1                                                          Fortune, Miss. Mabel Helen  female  23.00      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                                                              Celotti, Mr. Francesco    male  24.00      0      0              343275    8.0500              NaN        S
90            91         0       3                                                                Christmann, Mr. Emil    male  29.00      0      0              343276    8.0500              NaN        S
91            92         0       3                                                          Andreasson, Mr. Paul Edvin    male  20.00      0      0              347466    7.8542              NaN        S
92            93         0       1                                                         Chaffee, Mr. Herbert Fuller    male  46.00      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                                                             Dean, Mr. Bertram Frank    male  26.00      1      2           C.A. 2315   20.5750              NaN        S
94            95         0       3                                                                   Coxon, Mr. Daniel    male  59.00      0      0              364500    7.2500              NaN        S
95            96         0       3                                                         Shorney, Mr. Charles Joseph    male    NaN      0      0              374910    8.0500              NaN        S
96            97         0       1                                                           Goldschmidt, Mr. George B    male  71.00      0      0            PC 17754   34.6542               A5        C

In [ ]:
print(df.shape)

(891, 12)

In [ ]:
df.describe(include=[int])

       PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [ ]:
df.describe(include=[float])

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [ ]:
df.describe(exclude=[int])

,Name,Gender,Age,Ticket,Fare,Cabin,Embarked
count,891,891,714.000000,891,891.000000,204,889
unique,891,2,NaN,681,NaN,147,3
top,"Dooley, Mr. Patrick",male,NaN,347082,NaN,G6,S
freq,1,577,NaN,7,NaN,4,644
mean,NaN,NaN,29.699118,NaN,32.204208,NaN,NaN
std,NaN,NaN,14.526497,NaN,49.693429,NaN,NaN
min,NaN,NaN,0.420000,NaN,0.000000,NaN,NaN
25%,NaN,NaN,20.125000,NaN,7.910400,NaN,NaN
50%,NaN,NaN,28.000000,NaN,14.454200,NaN,NaN
75%,NaN,NaN,38.000000,NaN,31.000000,NaN,NaN
max,NaN,NaN,80.000000,NaN,512.329200,NaN,NaN

In [ ]:
df.describe(exclude=[float])

,PassengerId,Survived,Pclass,Name,Gender,SibSp,Parch,Ticket,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,891.000000,891.000000,891,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,681,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,347082,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,7,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,0.523008,0.381594,NaN,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,1.102743,0.806057,NaN,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,8.000000,6.000000,NaN,NaN,NaN

In [ ]:
df.duplicated().sum()
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0